### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by NeonLightning** [slastrina/cdromance_scraper#1]
when i try to run i get
```
Scraping: https://cdromance.com/sony-psp-dlc-list-psp-downloadable-content/
503
Queued 0 files for download
Starting

***************************

Done
```

**Comment by slastrina** [comment]
hi @NeonLightning, unfortunately they stuck the site behind cloudfare and it broke the scraper, not sure if it will be possible to scrape as is but ill have a look into it

**Comment by NeonLightning** [comment]
ah bummer been looking to find anywhere to bulk grab dlc. thanks for responding.

**Comment by slastrina** [comment]
i updated the code to bypass cloudfare, and ive updated the scraper to what seems like the new implementation but the onetime download key the site returns seems to be invalid, there is a required argument "post_id" on the download url but when provided with the data-id of the item to be downloaded the site no longer returns any key. Need to look into it at a later date when i have more time.

**Comment by NeonLightning** [comment]
well if i can help in some way i will. but i don't know python.(or really anything other than scripting languages)
