### ISSUE TITLE
Sigh...

### ISSUE THREAD

**Issue by RetroGameTalk** [slastrina/cdromance_scraper#2]
All this massive effort (7 years) to put together a cool place for people.
Yet everybody's looking for ways to consume CDR resources without visiting the page, or blocking the ads, don't realize maintaining the site UP requires a steep monthly bill that is getting harder to to pay each month.
Just another nail in the coffin, soon they'll be nothing to left to scrape.
Regards.

**Comment by slastrina** [comment]
Don't fret, the scraper doesn't work anymore anyway it was rendered useless a few days after I wrote it plus it only served one purpose at the time and that was to preserve the psp dlc it literally didn't work for any other part of the site. I've left the sourcecode here as a sample on using beautiful soup, I figure deleting source code in itself is a waste for others trying to learn for their own projects, cd romance is a great site with great resources but I won't lie the challenge of writing a scraper at the time was alot of fun. Hopefully cd romance doesn't go anywhere but if scraping is still an issue I'd suggest looking elsewhere
